### PR TITLE
Student model

### PR DESCRIPTION
**Pull request by SAchu47**
Student model

### CODE REVIEW

**Comment by sastaachar** [comment]
I think it is not a good idea to add this User api with aur app's api , cause i think in future we wil have user authentication from some official database . we can keep the jwt here but i suggest to move the user model and api to another demo api. @jeffin143 What do you think ?

**Comment by SAchu47** [comment]
> I think it is not a good idea to add this User api with aur app's api , cause i think in future we wil have user authentication from some official database . we can keep the jwt here but i suggest to move the user model and api to another demo api. @jeffin143 What do you think ?

The user authentication will be done using karunya ldap by forntend and for success response user will be saved as one-time login using OAuth  and the student db is required for the notification based on year, dept, groups, etc and future features might require it so.

**Comment by sastaachar** [comment]
for group clustering of the article the tags i'have added would be enough i think , For eg :
if you want a notification for 3 rd year cse students you can put a tag 3-yr-cse
and front end can filter it easily

**Comment by SAchu47** [comment]
> for group clustering of the articles the tags i'have added would be enough i think , For eg :
> if you want a notification for 3 rd year cse students you can put a tag 3-yr-cse
> and front end can filter it easily

Jeffin bhaiya told not to addon more data into frontend because we shouldn't log too much of data into the user's phone and if the teacher wants to send data to non-academic students likewise

**Comment by jeffin143** [comment]
> for group clustering of the articles the tags i'have added would be enough i think , For eg :
if you want a notification for 3 rd year 

How would you know ? a particular guy is in 3rd year group ? for 3rd year you can check roll no but how will you know custom group ?

**Comment by sastaachar** [comment]
> > for group clustering of the articles the tags i'have added would be enough i think , For eg :
> > if you want a notification for 3 rd year
> 
> How would you know ? a particular guy is in 3rd year group ? for 3rd year you can check roll no but how will you know custom group ?
> 
> jeffin is in ncc group and you are in nss ?
> now if you want to trigger nss related then whom should it go ? how will you decide ?
> and only show if that notification belongs to that group

frontend can add a track feature for a particular tag , like user will set  that he wants continues updates on a particular tag and the app will keep giving updates on that tag, similar to what Quora does or reddit we can follow tags , i think this will a easier approach that to create separate db to track the users.

**Comment by jeffin143** [comment]
@sastaachar I am lazy guy , I forgot to subscribe tag for placement group , then I will miss out on placement news , whereas our use case is irrespective of anything we want him to notify about placements ,how will you handle that ?

**Comment by jeffin143** [comment]
@sastaachar where will it that be stored, 
Suppose I want to see all the updates related to english tags , I hit subscribe where will that information be stored ? 
How will our software know which tag had user stored , since frontend is not persistent once app is closed everything is lost

**Comment by SAchu47** [comment]
We need to work fast dead line is coming @jeffin143  @sastaachar

**Comment by jeffin143** [comment]
@SAchu47 , I have solved the merge conflict, The test are failing because now we cannot use api without authenticating and hence Please make apt changes in Test as well

I recommend using `beforeEach()` block and authenticate the api, so that we can run the test

After the test passes and we conclude that it does not break anything we can merge this 


Rest looks good

**Pull request merged**
